name: Current Source
# Test the local lastfmget source code
# Triggered on pushes
on:
  - push

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: test
    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Set Up Environment
        run: scripts/actions/test_source/setup_env.sh

      - name: Run Tests
        working-directory: test
        run: scripts/actions/test_source/test.sh
