name: Unit Tests
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 src/lastfmget test/tests.py --select=E9,F63,F7,F82 --show-source --statistics

      - name: Set up environment
        run: |
          pip install --upgrade pip
          scripts/setuptest.sh

      - name: Run tests
        run: scripts/test.sh
