name: Latest Release
# Test the latest version of lastfmget from pip
# Triggered on Github releases (or manually)
on:
  workflow_dispatch
  release:
    types:
      - published

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up environment
        run: scripts/actions/setup_env.sh -release

      - name: Run tests
        run: scripts/actions/test.sh -release
