name: Unit Tests
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Lint (flake8)
        run: scripts/lint.sh

      - name: Set up environment
        env:
          CFG_FN: test/api_cfg.yaml
          API_URL: http://ws.audioscrobbler.com/2.0/
          API_KEY: ${{ secrets.TEST_API_KEY }}
          USER_AGENT: D3r3k23
          USE_CACHE: false
          CALL_RATE: 5
        run: |
          "Set up environment"
          echo "Generate api_cfg.yaml"
          pip install --disable-pip-version-check -qqq pyyaml
          python3 scripts/gen_api_cfg_yaml.py $CFG_FN $API_URL $API_KEY $USER_AGENT $USE_CACHE $CALL_RATE
          echo "Run scripts/setuptest.sh"
          scripts/setuptest.sh

      - name: Run tests
        run: scripts/test.sh
