name: Unit Tests
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: flake8 Lint
        run: scripts/lint.sh

      - name: Set Up Environment
        run: scripts/setupenv.sh

      - name: Run tests
        run: scripts/test.sh
